{{- if eq .Values.storage.type "azure" }}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ include "teamcity.fullname" . }}
provisioner: file.csi.azure.com # replace with "kubernetes.io/azure-file" if aks version is less than 1.21
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30
parameters:
  skuName: Standard_LRS
{{- end }}
{{- if eq .Values.storage.type "aws" }}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ include "teamcity.fullname" . }}
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: {{ .Values.storage.fsid}}
  directoryPerms: "700"
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "teamcity.fullname" . }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ include "teamcity.fullname" . }}
  resources:
    requests:
      storage: 20Gi