{{- if .Values.artifacts.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "teamcity.fullname" . }}
  labels:
    {{- include "teamcity.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn:  {{ .Values.artifacts.arn }}
{{- end }}
